name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: archtenet/platform-infra/.github/workflows/service-ci.yml@main
    with:
      service-name: notification-service
      helm-path: notification-service/helm
    secrets: inherit
